# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[profile.default]
evm_version = "cancun"
ffi = true
fs_permissions = [
	{ access = "read-write", path = ".gas-snapshots.md" },
	{ access = "read-write", path = ".forge-snapshots/" },
	{ access = "read", path = "./out" },
]
libs = [
	"lib",
]
out = "out"
script = 'script'
solc = "0.8.26"
src = "src"
test = 'test'

[fuzz]
runs = 1000
seed = '0x3e8'

[rpc_endpoints]
mainnet = "${RPC_MAINNET}"

[etherscan]
mainnet = { key = "${ETHERSCAN_MAINNET_KEY}" }
